openapi: 3.2.0
info:
  title: Patient Access Medication Request API
  description: Patient Access Endpoints for FHIR Resources
  version: '1.0'
servers:
- url: https://dev-int-api-gw.centene.com/fhir/v4/patientaccess
tags:
- name: Medication Request
paths:
  /MedicationRequest:
    get:
      tags:
      - Medication Request
      summary: Search all resources of type MedicationRequest based on a set of criteria
      operationId: searchMedicationRequest
      parameters:
      - name: intent
        in: query
        description: Returns prescriptions with different intents
        schema:
          type: string
      - name: patient
        in: query
        description: Returns prescriptions for a specific patient
        schema:
          type: string
      - name: status
        in: query
        description: Status of the prescription
        schema:
          type: string
      - name: _include
        in: query
        schema:
          type: string
          x-consoleDefault: application/json
        x-consoleDefault: application/json
      - name: _revinclude
        in: query
        schema:
          type: string
          x-consoleDefault: application/json
        x-consoleDefault: application/json
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MedicationRequest-search'
        '400':
          description: Bad request
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: invalid
                  details:
                    text: Invalid or badly formed MedicationRequest ID .
        '401':
          description: Unauthorized
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Unauthorized
                  details:
                    text: You are not authorized to view this MedicationRequest.
        '403':
          description: Forbidden
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: forbidden
                  details:
                    text: You are not allowed to view this MedicationRequest.
        '404':
          description: Not Found
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Found
                  details:
                    text: No MedicationRequest found with the provided ID.
        '500':
          description: InternalServerError
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: fatal
                  code: exception
                  details:
                    text: Internal server error. Please try again later
        '429':
          description: Too Many Requests
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Too Many Requests
                  details:
                    text: Too Many Requests for medication request with the provided ID.
        '501':
          description: Not Implemented
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Implemented
                  details:
                    text: The request for Medication request is Not Implemented
        '502':
          description: Bad gateway
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Bad gateway
                  details:
                    text: Bad gateway
        '503':
          description: Service Unavailable
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Service Unavailable
                  details:
                    text: Service Unavailable
        '504':
          description: Gateway Timeout
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Gateway Timeout
                  details:
                    text: Gateway Timeout
      security:
      - Bearer: []
  /MedicationRequest/{id}:
    get:
      tags:
      - Medication Request
      summary: Read the current state of the resource
      operationId: readMedicationRequest
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MedicationRequest'
        '400':
          description: Bad request
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: invalid
                  details:
                    text: Invalid or badly formed MedicationRequest ID .
        '401':
          description: Unauthorized
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Unauthorized
                  details:
                    text: You are not authorized to view this MedicationRequest.
        '403':
          description: Forbidden
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: forbidden
                  details:
                    text: You are not allowed to view this MedicationRequest.
        '404':
          description: Not Found
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Found
                  details:
                    text: No MedicationRequest found with the provided ID.
        '500':
          description: InternalServerError
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: fatal
                  code: exception
                  details:
                    text: Internal server error. Please try again later
        '429':
          description: Too Many Requests
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Too Many Requests
                  details:
                    text: Too Many Requests for medication request with the provided ID.
        '501':
          description: Not Implemented
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Implemented
                  details:
                    text: The request for medication request is Not Implemented
        '502':
          description: Bad gateway
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Bad gateway
                  details:
                    text: Bad gateway
        '503':
          description: Service Unavailable
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Service Unavailable
                  details:
                    text: Service Unavailable
        '504':
          description: Gateway Timeout
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Gateway Timeout
                  details:
                    text: Gateway Timeout
      security:
      - Bearer: []
components:
  schemas:
    MedicationRequest:
      required:
      - authoredOn
      - dosageInstruction
      - encounter
      - id
      - identifier
      - intent
      - medicationCodeableConcept
      - reportedBoolean
      - requester
      - resourceType
      - status
      - subject
      - text
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        text:
          required:
          - div
          - status
          type: object
          properties:
            status:
              minLength: 1
              type: string
            div:
              minLength: 1
              type: string
        identifier:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - system
            - use
            - value
            type: object
            properties:
              use:
                minLength: 1
                type: string
              system:
                minLength: 1
                type: string
              value:
                minLength: 1
                type: string
        status:
          minLength: 1
          type: string
        intent:
          minLength: 1
          type: string
        reportedBoolean:
          type: boolean
        medicationCodeableConcept:
          required:
          - coding
          - text
          type: object
          properties:
            coding:
              minItems: 1
              uniqueItems: true
              type: array
              items:
                required:
                - code
                - display
                - system
                type: object
                properties:
                  system:
                    minLength: 1
                    type: string
                  code:
                    minLength: 1
                    type: string
                  display:
                    minLength: 1
                    type: string
            text:
              minLength: 1
              type: string
        subject:
          required:
          - display
          - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
            display:
              minLength: 1
              type: string
        encounter:
          required:
          - display
          - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
            display:
              minLength: 1
              type: string
        authoredOn:
          minLength: 1
          type: string
        requester:
          required:
          - display
          - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
            display:
              minLength: 1
              type: string
        dosageInstruction:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - text
            type: object
            properties:
              text:
                minLength: 1
                type: string
      description: ''
    MedicationRequest-search:
      required:
      - entry
      - id
      - link
      - meta
      - resourceType
      - total
      - type
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        meta:
          required:
          - lastUpdated
          type: object
          properties:
            lastUpdated:
              minLength: 1
              type: string
        type:
          minLength: 1
          type: string
        total:
          type: number
        link:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - relation
            - url
            type: object
            properties:
              relation:
                minLength: 1
                type: string
              url:
                minLength: 1
                type: string
        entry:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - fullUrl
            type: object
            properties:
              fullUrl:
                minLength: 1
                type: string
              resource:
                required:
                - authoredOn
                - dosageInstruction
                - encounter
                - id
                - identifier
                - intent
                - medicationCodeableConcept
                - reportedBoolean
                - requester
                - resourceType
                - status
                - subject
                - text
                type: object
                properties:
                  resourceType:
                    minLength: 1
                    type: string
                  id:
                    minLength: 1
                    type: string
                  text:
                    required:
                    - div
                    - status
                    type: object
                    properties:
                      status:
                        minLength: 1
                        type: string
                      div:
                        minLength: 1
                        type: string
                  identifier:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - system
                      - use
                      - value
                      type: object
                      properties:
                        use:
                          minLength: 1
                          type: string
                        system:
                          minLength: 1
                          type: string
                        value:
                          minLength: 1
                          type: string
                  status:
                    minLength: 1
                    type: string
                  intent:
                    minLength: 1
                    type: string
                  reportedBoolean:
                    type: boolean
                  medicationCodeableConcept:
                    required:
                    - coding
                    - text
                    type: object
                    properties:
                      coding:
                        minItems: 1
                        uniqueItems: true
                        type: array
                        items:
                          required:
                          - code
                          - display
                          - system
                          type: object
                          properties:
                            system:
                              minLength: 1
                              type: string
                            code:
                              minLength: 1
                              type: string
                            display:
                              minLength: 1
                              type: string
                      text:
                        minLength: 1
                        type: string
                  subject:
                    required:
                    - display
                    - reference
                    type: object
                    properties:
                      reference:
                        minLength: 1
                        type: string
                      display:
                        minLength: 1
                        type: string
                  encounter:
                    required:
                    - display
                    - reference
                    type: object
                    properties:
                      reference:
                        minLength: 1
                        type: string
                      display:
                        minLength: 1
                        type: string
                  authoredOn:
                    minLength: 1
                    type: string
                  requester:
                    required:
                    - display
                    - reference
                    type: object
                    properties:
                      reference:
                        minLength: 1
                        type: string
                      display:
                        minLength: 1
                        type: string
                  dosageInstruction:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - text
                      type: object
                      properties:
                        text:
                          minLength: 1
                          type: string
      description: ''
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
