openapi: 3.2.0
info:
  title: Patient Access List API
  description: Patient Access Endpoints for FHIR Resources
  version: '1.0'
servers:
- url: https://dev-int-api-gw.centene.com/fhir/v4/patientaccess
tags:
- name: List
paths:
  /List:
    get:
      tags:
      - List
      summary: Search all resources of type List based on a set of criteria
      operationId: searchList
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/List-search'
        '400':
          description: Bad request
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: invalid
                  details:
                    text: Invalid or badly formed List ID .
        '401':
          description: Unauthorized
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Unauthorized
                  details:
                    text: You are not authorized to view this List.
        '403':
          description: Forbidden
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: forbidden
                  details:
                    text: You are not allowed to view this List.
        '404':
          description: Not Found
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Found
                  details:
                    text: No List found with the provided ID.
        '500':
          description: InternalServerError
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: fatal
                  code: exception
                  details:
                    text: Internal server error. Please try again later
        '429':
          description: Too Many Requests
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Too Many Requests
                  details:
                    text: Too Many Requests for List with the provided ID.
        '501':
          description: Not Implemented
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Implemented
                  details:
                    text: The request for List is Not Implemented
        '502':
          description: Bad gateway
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Bad gateway
                  details:
                    text: Bad gateway
        '503':
          description: Service Unavailable
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Service Unavailable
                  details:
                    text: Service Unavailable
        '504':
          description: Gateway Timeout
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Gateway Timeout
                  details:
                    text: Gateway Timeout
      parameters:
      - name: identifier
        in: query
        schema:
          type: string
        description: Business Identifier
      - name: _id
        in: query
        schema:
          type: string
        description: Logical id of resource
      - name: item
        in: query
        schema:
          type: string
        description: MedicationKnowledge resource id
      - name: status
        in: query
        schema:
          type: string
        description: CoveragePlan status - 'current', 'retired', or 'entered-in-error'
      - name: _page
        in: query
        schema:
          type: number
        description: Page for paginated results
      security:
      - Bearer: []
  /List/{id}:
    get:
      tags:
      - List
      summary: Read the current state of the resource
      operationId: readList
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/List-read'
        '400':
          description: Bad request
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: invalid
                  details:
                    text: Invalid or badly formed List ID .
        '401':
          description: Unauthorized
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Unauthorized
                  details:
                    text: You are not authorized to view this List.
        '403':
          description: Forbidden
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: forbidden
                  details:
                    text: You are not allowed to view this List.
        '404':
          description: Not Found
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Found
                  details:
                    text: No List found with the provided ID.
        '500':
          description: InternalServerError
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: fatal
                  code: exception
                  details:
                    text: Internal server error. Please try again later
        '429':
          description: Too Many Requests
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Too Many Requests
                  details:
                    text: Too Many Requests for List with the provided ID.
        '501':
          description: Not Implemented
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Implemented
                  details:
                    text: The request for List is Not Implemented
        '502':
          description: Bad gateway
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Bad gateway
                  details:
                    text: Bad gateway
        '503':
          description: Service Unavailable
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Service Unavailable
                  details:
                    text: Service Unavailable
        '504':
          description: Gateway Timeout
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Gateway Timeout
                  details:
                    text: Gateway Timeout
      security:
      - Bearer: []
components:
  schemas:
    List-read:
      description: ''
      type: object
      properties:
        resourceType:
          type: string
          minLength: 1
        id:
          type: string
          minLength: 1
        meta:
          type: object
          properties:
            versionId:
              type: string
              minLength: 1
            lastUpdated:
              type: string
              minLength: 1
            profile:
              type: array
              items:
                properties: {}
          required:
          - versionId
          - lastUpdated
          - profile
        extension:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            required:
            - url
            properties:
              url:
                type: string
                minLength: 1
              extension:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  required:
                  - url
                  properties:
                    url:
                      type: string
                      minLength: 1
                    valueCodeableConcept:
                      type: object
                      properties:
                        coding:
                          type: array
                          uniqueItems: true
                          minItems: 1
                          items:
                            required:
                            - system
                            - code
                            - display
                            properties:
                              system:
                                type: string
                                minLength: 1
                              code:
                                type: string
                                minLength: 1
                              display:
                                type: string
                                minLength: 1
                      required:
                      - coding
        identifier:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            required:
            - value
            properties:
              value:
                type: string
                minLength: 1
        status:
          type: string
          minLength: 1
        mode:
          type: string
          minLength: 1
        title:
          type: string
          minLength: 1
        date:
          type: string
          minLength: 1
      required:
      - resourceType
      - id
      - meta
      - extension
      - identifier
      - status
      - mode
      - title
      - date
    List-search:
      description: ''
      type: object
      properties:
        resourceType:
          type: string
          minLength: 1
        id:
          type: string
          minLength: 1
        meta:
          type: object
          properties:
            lastUpdated:
              type: string
              minLength: 1
          required:
          - lastUpdated
        type:
          type: string
          minLength: 1
        total:
          type: number
        link:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            required:
            - relation
            - url
            properties:
              relation:
                type: string
                minLength: 1
              url:
                type: string
                minLength: 1
        entry:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            required:
            - fullUrl
            properties:
              fullUrl:
                type: string
                minLength: 1
              resource:
                type: object
                properties:
                  resourceType:
                    type: string
                    minLength: 1
                  id:
                    type: string
                    minLength: 1
                  meta:
                    type: object
                    properties:
                      versionId:
                        type: string
                        minLength: 1
                      lastUpdated:
                        type: string
                        minLength: 1
                      profile:
                        type: array
                        items:
                          properties: {}
                    required:
                    - versionId
                    - lastUpdated
                    - profile
                  extension:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                      - url
                      properties:
                        url:
                          type: string
                          minLength: 1
                        extension:
                          type: array
                          uniqueItems: true
                          minItems: 1
                          items:
                            required:
                            - url
                            properties:
                              url:
                                type: string
                                minLength: 1
                              valueCodeableConcept:
                                type: object
                                properties:
                                  coding:
                                    type: array
                                    uniqueItems: true
                                    minItems: 1
                                    items:
                                      required:
                                      - system
                                      - code
                                      - display
                                      properties:
                                        system:
                                          type: string
                                          minLength: 1
                                        code:
                                          type: string
                                          minLength: 1
                                        display:
                                          type: string
                                          minLength: 1
                                required:
                                - coding
                  identifier:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                      - value
                      properties:
                        value:
                          type: string
                          minLength: 1
                  status:
                    type: string
                    minLength: 1
                  mode:
                    type: string
                    minLength: 1
                  title:
                    type: string
                    minLength: 1
                  date:
                    type: string
                    minLength: 1
                required:
                - resourceType
                - id
                - meta
                - extension
                - identifier
                - status
                - mode
                - title
                - date
      required:
      - resourceType
      - id
      - meta
      - type
      - total
      - link
      - entry
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
