openapi: 3.2.0
info:
  title: Patient Access Explanation Of Benefit API
  description: Patient Access Endpoints for FHIR Resources
  version: '1.0'
servers:
- url: https://dev-int-api-gw.centene.com/fhir/v4/patientaccess
tags:
- name: ExplanationOfBenefit
paths:
  /ExplanationOfBenefit:
    get:
      tags:
      - ExplanationOfBenefit
      summary: Search all resources of type ExplanationOfBenefit based on a set of criteria
      operationId: searchExplanationOfBenefit
      parameters:
      - name: service-date
        in: query
        schema:
          type: string
          format: date
      - name: patient
        in: query
        description: The reference to the patient
        schema:
          type: string
      - name: _id
        in: query
        description: The ID of the resource
        schema:
          type: string
      - name: type
        in: query
        schema:
          type: string
      - name: _lastUpdated
        in: query
        schema:
          type: string
      - name: identifier
        in: query
        description: The business identifier of the Explanation of Benefit
        schema:
          type: string
      - name: service-start-date
        in: query
        description: Starting Date of the service for the EOB. The service-start-date search parameter simplifies search, since a client doesn't need to know that for inpatient and outpatient institutional EOB dates they need to search by billablePeriod.start, for a pharmacy EOB by item.servicedDate, for a professional and non-clinician EOB - by item.servicedPeriod.start and for an oral EOB - by item.servicedPeriod.start.
        schema:
          type: string
          format: date
      - name: billable-period-start
        description: Starting Date of the service for the EOB using billablePeriod.period.start. The billable-period-start search parameter using the billablePeriod.period.start provides results with the earliest billablePeriod.start from a professional and non-clinician EOB or an oral EOB.
        in: query
        schema:
          type: string
          format: date
      - name: _include
        in: query
        schema:
          type: string
          x-consoleDefault: application/json
        x-consoleDefault: application/json
      - name: _page
        in: query
        schema:
          type: number
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExplanationOfBenefit-search'
        '400':
          description: Bad request
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: invalid
                  details:
                    text: Invalid or badly formed ExplanationOfBenefit ID .
        '401':
          description: Unauthorized
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Unauthorized
                  details:
                    text: You are not authorized to view this ExplanationOfBenefit.
        '403':
          description: Forbidden
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: forbidden
                  details:
                    text: You are not allowed to view this ExplanationOfBenefit.
        '404':
          description: Not Found
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Found
                  details:
                    text: No ExplanationOfBenefit found with the provided ID.
        '500':
          description: InternalServerError
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: fatal
                  code: exception
                  details:
                    text: Internal server error. Please try again later
        '429':
          description: Too Many Requests
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Too Many Requests
                  details:
                    text: Too Many Requests for Explanation of benefit with the provided ID.
        '501':
          description: Not Implemented
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Implemented
                  details:
                    text: The request for Explanation of benefit is Not Implemented
        '502':
          description: Bad gateway
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Bad gateway
                  details:
                    text: Bad gateway
        '503':
          description: Service Unavailable
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Service Unavailable
                  details:
                    text: Service Unavailable
        '504':
          description: Gateway Timeout
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Gateway Timeout
                  details:
                    text: Gateway Timeout
      security:
      - Bearer: []
  /ExplanationOfBenefit/{id}:
    get:
      tags:
      - ExplanationOfBenefit
      summary: Read the current state of the resource
      operationId: readExplanationOfBenefit
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: _page
        in: query
        schema:
          type: number
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExplanationOfBenefit'
        '400':
          description: Bad request
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: invalid
                  details:
                    text: Invalid or badly formed ExplanationOfBenefit ID .
        '401':
          description: Unauthorized
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Unauthorized
                  details:
                    text: You are not authorized to view this ExplanationOfBenefit.
        '403':
          description: Forbidden
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: forbidden
                  details:
                    text: You are not allowed to view this ExplanationOfBenefit.
        '404':
          description: Not Found
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Found
                  details:
                    text: No ExplanationOfBenefit found with the provided ID.
        '500':
          description: InternalServerError
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: fatal
                  code: exception
                  details:
                    text: Internal server error. Please try again later
        '429':
          description: Too Many Requests
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Too Many Requests
                  details:
                    text: Too Many Requests for explanation of benefit with the provided ID.
        '501':
          description: Not Implemented
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Implemented
                  details:
                    text: The request for explanation of benefit is Not Implemented
        '502':
          description: Bad gateway
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Bad gateway
                  details:
                    text: Bad gateway
        '503':
          description: Service Unavailable
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Service Unavailable
                  details:
                    text: Service Unavailable
        '504':
          description: Gateway Timeout
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Gateway Timeout
                  details:
                    text: Gateway Timeout
      security:
      - Bearer: []
components:
  schemas:
    ExplanationOfBenefit:
      required:
      - adjudication
      - billablePeriod
      - created
      - diagnosis
      - id
      - identifier
      - insurance
      - insurer
      - language
      - meta
      - outcome
      - patient
      - provider
      - resourceType
      - status
      - subType
      - supportingInfo
      - text
      - total
      - type
      - use
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        meta:
          required:
          - lastUpdated
          - profile
          type: object
          properties:
            lastUpdated:
              minLength: 1
              type: string
            profile:
              type: array
              items:
                type: object
                properties: {}
        language:
          minLength: 1
          type: string
        text:
          required:
          - div
          - status
          type: object
          properties:
            status:
              minLength: 1
              type: string
            div:
              minLength: 1
              type: string
        identifier:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - system
            - value
            type: object
            properties:
              type:
                required:
                - coding
                type: object
                properties:
                  coding:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - code
                      - system
                      type: object
                      properties:
                        system:
                          minLength: 1
                          type: string
                        code:
                          minLength: 1
                          type: string
              system:
                minLength: 1
                type: string
              value:
                minLength: 1
                type: string
        status:
          minLength: 1
          type: string
        type:
          required:
          - coding
          - text
          type: object
          properties:
            coding:
              minItems: 1
              uniqueItems: true
              type: array
              items:
                required:
                - code
                - system
                type: object
                properties:
                  system:
                    minLength: 1
                    type: string
                  code:
                    minLength: 1
                    type: string
            text:
              minLength: 1
              type: string
        subType:
          required:
          - coding
          - text
          type: object
          properties:
            coding:
              minItems: 1
              uniqueItems: true
              type: array
              items:
                required:
                - code
                - system
                type: object
                properties:
                  system:
                    minLength: 1
                    type: string
                  code:
                    minLength: 1
                    type: string
            text:
              minLength: 1
              type: string
        use:
          minLength: 1
          type: string
        patient:
          required:
          - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
        billablePeriod:
          required:
          - end
          - start
          type: object
          properties:
            start:
              minLength: 1
              type: string
            end:
              minLength: 1
              type: string
        created:
          minLength: 1
          type: string
        insurer:
          required:
          - display
          - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
            display:
              minLength: 1
              type: string
        provider:
          required:
          - display
          - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
            display:
              minLength: 1
              type: string
        outcome:
          minLength: 1
          type: string
        supportingInfo:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - sequence
            type: object
            properties:
              sequence:
                type: number
              category:
                required:
                - coding
                type: object
                properties:
                  coding:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - code
                      - system
                      type: object
                      properties:
                        system:
                          minLength: 1
                          type: string
                        code:
                          minLength: 1
                          type: string
              timingPeriod:
                required:
                - end
                - start
                type: object
                properties:
                  start:
                    minLength: 1
                    type: string
                  end:
                    minLength: 1
                    type: string
        diagnosis:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - sequence
            type: object
            properties:
              sequence:
                type: number
              diagnosisCodeableConcept:
                required:
                - coding
                type: object
                properties:
                  coding:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - code
                      - system
                      type: object
                      properties:
                        system:
                          minLength: 1
                          type: string
                        code:
                          minLength: 1
                          type: string
              type:
                minItems: 1
                uniqueItems: true
                type: array
                items:
                  type: object
                  properties:
                    coding:
                      minItems: 1
                      uniqueItems: true
                      type: array
                      items:
                        required:
                        - code
                        - system
                        type: object
                        properties:
                          system:
                            minLength: 1
                            type: string
                          code:
                            minLength: 1
                            type: string
        insurance:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - focal
            type: object
            properties:
              focal:
                type: boolean
              coverage:
                required:
                - reference
                type: object
                properties:
                  reference:
                    minLength: 1
                    type: string
        adjudication:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: object
            properties:
              category:
                required:
                - coding
                - text
                type: object
                properties:
                  coding:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - code
                      - system
                      type: object
                      properties:
                        system:
                          minLength: 1
                          type: string
                        code:
                          minLength: 1
                          type: string
                  text:
                    minLength: 1
                    type: string
              amount:
                required:
                - currency
                - value
                type: object
                properties:
                  value:
                    type: number
                  currency:
                    minLength: 1
                    type: string
        total:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: object
            properties:
              category:
                required:
                - coding
                - text
                type: object
                properties:
                  coding:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - code
                      - system
                      type: object
                      properties:
                        system:
                          minLength: 1
                          type: string
                        code:
                          minLength: 1
                          type: string
                  text:
                    minLength: 1
                    type: string
              amount:
                required:
                - currency
                - value
                type: object
                properties:
                  value:
                    type: number
                  currency:
                    minLength: 1
                    type: string
      description: ''
    ExplanationOfBenefit-search:
      required:
      - entry
      - id
      - link
      - meta
      - resourceType
      - total
      - type
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        meta:
          required:
          - lastUpdated
          type: object
          properties:
            lastUpdated:
              minLength: 1
              type: string
        type:
          minLength: 1
          type: string
        total:
          type: number
        link:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - relation
            - url
            type: object
            properties:
              relation:
                minLength: 1
                type: string
              url:
                minLength: 1
                type: string
        entry:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - fullUrl
            type: object
            properties:
              fullUrl:
                minLength: 1
                type: string
              resource:
                required:
                - adjudication
                - billablePeriod
                - created
                - diagnosis
                - id
                - identifier
                - insurance
                - insurer
                - language
                - meta
                - outcome
                - patient
                - provider
                - resourceType
                - status
                - subType
                - supportingInfo
                - text
                - total
                - type
                - use
                type: object
                properties:
                  resourceType:
                    minLength: 1
                    type: string
                  id:
                    minLength: 1
                    type: string
                  meta:
                    required:
                    - lastUpdated
                    - profile
                    type: object
                    properties:
                      lastUpdated:
                        minLength: 1
                        type: string
                      profile:
                        type: array
                        items:
                          type: object
                          properties: {}
                  language:
                    minLength: 1
                    type: string
                  text:
                    required:
                    - div
                    - status
                    type: object
                    properties:
                      status:
                        minLength: 1
                        type: string
                      div:
                        minLength: 1
                        type: string
                  identifier:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - system
                      - value
                      type: object
                      properties:
                        type:
                          required:
                          - coding
                          type: object
                          properties:
                            coding:
                              minItems: 1
                              uniqueItems: true
                              type: array
                              items:
                                required:
                                - code
                                - system
                                type: object
                                properties:
                                  system:
                                    minLength: 1
                                    type: string
                                  code:
                                    minLength: 1
                                    type: string
                        system:
                          minLength: 1
                          type: string
                        value:
                          minLength: 1
                          type: string
                  status:
                    minLength: 1
                    type: string
                  type:
                    required:
                    - coding
                    - text
                    type: object
                    properties:
                      coding:
                        minItems: 1
                        uniqueItems: true
                        type: array
                        items:
                          required:
                          - code
                          - system
                          type: object
                          properties:
                            system:
                              minLength: 1
                              type: string
                            code:
                              minLength: 1
                              type: string
                      text:
                        minLength: 1
                        type: string
                  subType:
                    required:
                    - coding
                    - text
                    type: object
                    properties:
                      coding:
                        minItems: 1
                        uniqueItems: true
                        type: array
                        items:
                          required:
                          - code
                          - system
                          type: object
                          properties:
                            system:
                              minLength: 1
                              type: string
                            code:
                              minLength: 1
                              type: string
                      text:
                        minLength: 1
                        type: string
                  use:
                    minLength: 1
                    type: string
                  patient:
                    required:
                    - reference
                    type: object
                    properties:
                      reference:
                        minLength: 1
                        type: string
                  billablePeriod:
                    required:
                    - end
                    - start
                    type: object
                    properties:
                      start:
                        minLength: 1
                        type: string
                      end:
                        minLength: 1
                        type: string
                  created:
                    minLength: 1
                    type: string
                  insurer:
                    required:
                    - display
                    - reference
                    type: object
                    properties:
                      reference:
                        minLength: 1
                        type: string
                      display:
                        minLength: 1
                        type: string
                  provider:
                    required:
                    - display
                    - reference
                    type: object
                    properties:
                      reference:
                        minLength: 1
                        type: string
                      display:
                        minLength: 1
                        type: string
                  outcome:
                    minLength: 1
                    type: string
                  supportingInfo:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - sequence
                      type: object
                      properties:
                        sequence:
                          type: number
                        category:
                          required:
                          - coding
                          type: object
                          properties:
                            coding:
                              minItems: 1
                              uniqueItems: true
                              type: array
                              items:
                                required:
                                - code
                                - system
                                type: object
                                properties:
                                  system:
                                    minLength: 1
                                    type: string
                                  code:
                                    minLength: 1
                                    type: string
                        timingPeriod:
                          required:
                          - end
                          - start
                          type: object
                          properties:
                            start:
                              minLength: 1
                              type: string
                            end:
                              minLength: 1
                              type: string
                  diagnosis:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - sequence
                      type: object
                      properties:
                        sequence:
                          type: number
                        diagnosisCodeableConcept:
                          required:
                          - coding
                          type: object
                          properties:
                            coding:
                              minItems: 1
                              uniqueItems: true
                              type: array
                              items:
                                required:
                                - code
                                - system
                                type: object
                                properties:
                                  system:
                                    minLength: 1
                                    type: string
                                  code:
                                    minLength: 1
                                    type: string
                        type:
                          minItems: 1
                          uniqueItems: true
                          type: array
                          items:
                            type: object
                            properties:
                              coding:
                                minItems: 1
                                uniqueItems: true
                                type: array
                                items:
                                  required:
                                  - code
                                  - system
                                  type: object
                                  properties:
                                    system:
                                      minLength: 1
                                      type: string
                                    code:
                                      minLength: 1
                                      type: string
                  insurance:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - focal
                      type: object
                      properties:
                        focal:
                          type: boolean
                        coverage:
                          required:
                          - reference
                          type: object
                          properties:
                            reference:
                              minLength: 1
                              type: string
                  adjudication:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      type: object
                      properties:
                        category:
                          required:
                          - coding
                          - text
                          type: object
                          properties:
                            coding:
                              minItems: 1
                              uniqueItems: true
                              type: array
                              items:
                                required:
                                - code
                                - system
                                type: object
                                properties:
                                  system:
                                    minLength: 1
                                    type: string
                                  code:
                                    minLength: 1
                                    type: string
                            text:
                              minLength: 1
                              type: string
                        amount:
                          required:
                          - currency
                          - value
                          type: object
                          properties:
                            value:
                              type: number
                            currency:
                              minLength: 1
                              type: string
                  total:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      type: object
                      properties:
                        category:
                          required:
                          - coding
                          - text
                          type: object
                          properties:
                            coding:
                              minItems: 1
                              uniqueItems: true
                              type: array
                              items:
                                required:
                                - code
                                - system
                                type: object
                                properties:
                                  system:
                                    minLength: 1
                                    type: string
                                  code:
                                    minLength: 1
                                    type: string
                            text:
                              minLength: 1
                              type: string
                        amount:
                          required:
                          - currency
                          - value
                          type: object
                          properties:
                            value:
                              type: number
                            currency:
                              minLength: 1
                              type: string
      description: ''
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
