openapi: 3.2.0
info:
  title: Access Patient API
  description: Patient Access Endpoints for FHIR Resources
  version: '1.0'
servers:
- url: https://dev-int-api-gw.centene.com/fhir/v4/patientaccess
tags:
- name: Patient
paths:
  /Patient:
    get:
      tags:
      - Patient
      summary: Search all resources of type Patient based on a set of criteria
      operationId: searchPatient
      parameters:
      - name: _id
        in: query
        description: A patient's Identifier
        schema:
          type: string
      - name: identifier
        in: query
        description: A patient's Identifier
        schema:
          type: string
      - name: name
        in: query
        description: A server defined search that may match any of the string fields in the HumanName, including family, give, prefix, suffix, suffix, and/or text
        schema:
          type: string
      - name: gender
        in: query
        description: A patient's Gender
        schema:
          type: string
      - name: birthdate
        in: query
        description: A patient's birthdate
        schema:
          type: string
      - name: _revinclude
        in: query
        schema:
          type: string
          x-consoleDefault: application/json
        x-consoleDefault: application/json
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Practitioner-search'
        '400':
          description: Bad request
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: invalid
                  details:
                    text: Invalid or badly formed Patient ID .
        '401':
          description: Unauthorized
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Unauthorized
                  details:
                    text: You are not authorized to view this Patient.
        '403':
          description: Forbidden
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: forbidden
                  details:
                    text: You are not allowed to view this Patient.
        '404':
          description: Not Found
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Found
                  details:
                    text: No Patient found with the provided ID.
        '500':
          description: InternalServerError
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: fatal
                  code: exception
                  details:
                    text: Internal server error. Please try again later
        '429':
          description: Too Many Requests
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Too Many Requests
                  details:
                    text: Too Many Requests for patient with the provided ID.
        '501':
          description: Not Implemented
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Implemented
                  details:
                    text: The request for patient is Not Implemented
        '502':
          description: Bad gateway
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Bad gateway
                  details:
                    text: Bad gateway
        '503':
          description: Service Unavailable
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Service Unavailable
                  details:
                    text: Service Unavailable
        '504':
          description: Gateway Timeout
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Gateway Timeout
                  details:
                    text: Gateway Timeout
      security:
      - Bearer: []
  /Patient/{id}:
    get:
      tags:
      - Patient
      summary: Read the current state of the resource
      operationId: readPatient
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Patient'
        '400':
          description: Bad request
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: invalid
                  details:
                    text: Invalid or badly formed Patient ID .
        '401':
          description: Unauthorized
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Unauthorized
                  details:
                    text: You are not authorized to view this Patient.
        '403':
          description: Forbidden
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: forbidden
                  details:
                    text: You are not allowed to view this Patient.
        '404':
          description: Not Found
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Found
                  details:
                    text: No Patient found with the provided ID.
        '500':
          description: InternalServerError
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: fatal
                  code: exception
                  details:
                    text: Internal server error. Please try again later
        '429':
          description: Too Many Requests
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Too Many Requests
                  details:
                    text: Too Many Requests for patient with the provided ID.
        '501':
          description: Not Implemented
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Implemented
                  details:
                    text: The request for patient is Not Implemented
        '502':
          description: Bad gateway
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Bad gateway
                  details:
                    text: Bad gateway
        '503':
          description: Service Unavailable
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Service Unavailable
                  details:
                    text: Service Unavailable
        '504':
          description: Gateway Timeout
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Gateway Timeout
                  details:
                    text: Gateway Timeout
      security:
      - Bearer: []
components:
  schemas:
    Patient:
      required:
      - active
      - address
      - birthDate
      - gender
      - id
      - identifier
      - language
      - maritalStatus
      - meta
      - name
      - resourceType
      - telecom
      - text
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        meta:
          required:
          - lastUpdated
          - profile
          type: object
          properties:
            lastUpdated:
              minLength: 1
              type: string
            profile:
              type: array
              items:
                type: object
                properties: {}
        language:
          minLength: 1
          type: string
        text:
          required:
          - div
          - status
          type: object
          properties:
            status:
              minLength: 1
              type: string
            div:
              minLength: 1
              type: string
        identifier:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - system
            - value
            type: object
            properties:
              type:
                required:
                - coding
                type: object
                properties:
                  coding:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - code
                      - system
                      type: object
                      properties:
                        system:
                          minLength: 1
                          type: string
                        code:
                          minLength: 1
                          type: string
              system:
                minLength: 1
                type: string
              value:
                minLength: 1
                type: string
        active:
          type: boolean
        name:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - family
            type: object
            properties:
              family:
                minLength: 1
                type: string
              given:
                type: array
                items:
                  type: object
                  properties: {}
        telecom:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - rank
            - system
            - value
            type: object
            properties:
              system:
                minLength: 1
                type: string
              value:
                minLength: 1
                type: string
              rank:
                type: number
        gender:
          minLength: 1
          type: string
        birthDate:
          minLength: 1
          type: string
        address:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - city
            - postalCode
            - state
            - type
            type: object
            properties:
              type:
                minLength: 1
                type: string
              line:
                type: array
                items:
                  type: object
                  properties: {}
              city:
                minLength: 1
                type: string
              state:
                minLength: 1
                type: string
              postalCode:
                minLength: 1
                type: string
        maritalStatus:
          required:
          - coding
          type: object
          properties:
            coding:
              minItems: 1
              uniqueItems: true
              type: array
              items:
                required:
                - code
                - system
                type: object
                properties:
                  system:
                    minLength: 1
                    type: string
                  code:
                    minLength: 1
                    type: string
      description: ''
    Practitioner-search:
      required:
      - entry
      - id
      - link
      - meta
      - resourceType
      - total
      - type
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        meta:
          required:
          - lastUpdated
          type: object
          properties:
            lastUpdated:
              minLength: 1
              type: string
        type:
          minLength: 1
          type: string
        total:
          type: number
        link:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - relation
            - url
            type: object
            properties:
              relation:
                minLength: 1
                type: string
              url:
                minLength: 1
                type: string
        entry:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - fullUrl
            type: object
            properties:
              fullUrl:
                minLength: 1
                type: string
              resource:
                required:
                - active
                - id
                - identifier
                - meta
                - name
                - resourceType
                - text
                type: object
                properties:
                  resourceType:
                    minLength: 1
                    type: string
                  id:
                    minLength: 1
                    type: string
                  meta:
                    required:
                    - lastUpdated
                    - profile
                    type: object
                    properties:
                      lastUpdated:
                        minLength: 1
                        type: string
                      profile:
                        type: array
                        items:
                          type: object
                          properties: {}
                  text:
                    required:
                    - div
                    - status
                    type: object
                    properties:
                      status:
                        minLength: 1
                        type: string
                      div:
                        minLength: 1
                        type: string
                  identifier:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - system
                      - value
                      type: object
                      properties:
                        type:
                          required:
                          - coding
                          - text
                          type: object
                          properties:
                            coding:
                              minItems: 1
                              uniqueItems: true
                              type: array
                              items:
                                required:
                                - code
                                - display
                                - system
                                type: object
                                properties:
                                  system:
                                    minLength: 1
                                    type: string
                                  code:
                                    minLength: 1
                                    type: string
                                  display:
                                    minLength: 1
                                    type: string
                            text:
                              minLength: 1
                              type: string
                        system:
                          minLength: 1
                          type: string
                        value:
                          minLength: 1
                          type: string
                  active:
                    type: boolean
                  name:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - family
                      type: object
                      properties:
                        family:
                          minLength: 1
                          type: string
                        given:
                          type: array
                          items:
                            type: object
                            properties: {}
                        prefix:
                          type: array
                          items:
                            type: object
                            properties: {}
      description: ''
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
