openapi: 3.2.0
info:
  title: Patient Access Coverage API
  description: Patient Access Endpoints for FHIR Resources
  version: '1.0'
servers:
- url: https://dev-int-api-gw.centene.com/fhir/v4/patientaccess
tags:
- name: Coverage
paths:
  /Coverage:
    get:
      tags:
      - Coverage
      summary: Search all resources of type Coverage based on a set of criteria
      operationId: searchCoverage
      parameters:
      - name: _id
        in: query
        description: Logical id of this artifact
        schema:
          type: string
      - name: _include
        in: query
        schema:
          type: string
          x-consoleDefault: application/json
        x-consoleDefault: application/json
      - name: _page
        in: query
        schema:
          type: number
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Coverage-search'
        '400':
          description: Bad request
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: invalid
                  details:
                    text: Invalid or badly formed Coverage ID .
        '401':
          description: Unauthorized
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Unauthorized
                  details:
                    text: You are not authorized to view this Coverage.
        '403':
          description: Forbidden
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: forbidden
                  details:
                    text: You are not allowed to view this Coverage.
        '404':
          description: Not Found
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Found
                  details:
                    text: No Coverage found with the provided ID.
        '500':
          description: InternalServerError
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: fatal
                  code: exception
                  details:
                    text: Internal server error. Please try again later
        '429':
          description: Too Many Requests
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Too Many Requests
                  details:
                    text: Too Many Requests for coverage with the provided ID.
        '501':
          description: Not Implemented
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Implemented
                  details:
                    text: The request for coverage is Not Implemented
        '502':
          description: Bad gateway
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Bad gateway
                  details:
                    text: Bad gateway
        '503':
          description: Service Unavailable
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Service Unavailable
                  details:
                    text: Service Unavailable
        '504':
          description: Gateway Timeout
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Gateway Timeout
                  details:
                    text: Gateway Timeout
      security:
      - Bearer: []
  /Coverage/{id}:
    get:
      tags:
      - Coverage
      summary: Read the current state of the resource
      operationId: readCoverage
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: _page
        in: query
        schema:
          type: number
      responses:
        '200':
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Coverage'
        '400':
          description: Bad request
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: invalid
                  details:
                    text: Invalid or badly formed Coverage ID .
        '401':
          description: Unauthorized
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Unauthorized
                  details:
                    text: You are not authorized to view this Coverage.
        '403':
          description: Forbidden
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: forbidden
                  details:
                    text: You are not allowed to view this Coverage.
        '404':
          description: Not Found
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Found
                  details:
                    text: No Coverage found with the provided ID.
        '500':
          description: InternalServerError
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: fatal
                  code: exception
                  details:
                    text: Internal server error. Please try again later
        '429':
          description: Too Many Requests
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Too Many Requests
                  details:
                    text: Too Many Requests for coverage with the provided ID.
        '501':
          description: Not Implemented
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Not Implemented
                  details:
                    text: The request for coverage is Not Implemented
        '502':
          description: Bad gateway
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Bad gateway
                  details:
                    text: Bad gateway
        '503':
          description: Service Unavailable
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Service Unavailable
                  details:
                    text: Service Unavailable
        '504':
          description: Gateway Timeout
          content:
            '*/*':
              example:
                resourceType: OperationOutcome
                issue:
                  severity: error
                  code: Gateway Timeout
                  details:
                    text: Gateway Timeout
      security:
      - Bearer: []
components:
  schemas:
    Coverage-search:
      required:
      - entry
      - id
      - link
      - meta
      - resourceType
      - total
      - type
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        meta:
          required:
          - lastUpdated
          type: object
          properties:
            lastUpdated:
              minLength: 1
              type: string
        type:
          minLength: 1
          type: string
        total:
          type: number
        link:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - relation
            - url
            type: object
            properties:
              relation:
                minLength: 1
                type: string
              url:
                minLength: 1
                type: string
        entry:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - fullUrl
            type: object
            properties:
              fullUrl:
                minLength: 1
                type: string
              resource:
                required:
                - beneficiary
                - class
                - dependent
                - id
                - identifier
                - language
                - meta
                - network
                - payor
                - period
                - policyHolder
                - relationship
                - resourceType
                - status
                - subscriber
                - subscriberId
                - text
                - type
                type: object
                properties:
                  resourceType:
                    minLength: 1
                    type: string
                  id:
                    minLength: 1
                    type: string
                  meta:
                    required:
                    - lastUpdated
                    - profile
                    type: object
                    properties:
                      lastUpdated:
                        minLength: 1
                        type: string
                      profile:
                        type: array
                        items:
                          type: object
                          properties: {}
                  language:
                    minLength: 1
                    type: string
                  text:
                    required:
                    - div
                    - status
                    type: object
                    properties:
                      status:
                        minLength: 1
                        type: string
                      div:
                        minLength: 1
                        type: string
                  identifier:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - system
                      - value
                      type: object
                      properties:
                        type:
                          required:
                          - coding
                          type: object
                          properties:
                            coding:
                              minItems: 1
                              uniqueItems: true
                              type: array
                              items:
                                required:
                                - code
                                - system
                                type: object
                                properties:
                                  system:
                                    minLength: 1
                                    type: string
                                  code:
                                    minLength: 1
                                    type: string
                        system:
                          minLength: 1
                          type: string
                        value:
                          minLength: 1
                          type: string
                  status:
                    minLength: 1
                    type: string
                  type:
                    required:
                    - coding
                    - text
                    type: object
                    properties:
                      coding:
                        minItems: 1
                        uniqueItems: true
                        type: array
                        items:
                          required:
                          - code
                          - system
                          type: object
                          properties:
                            system:
                              minLength: 1
                              type: string
                            code:
                              minLength: 1
                              type: string
                      text:
                        minLength: 1
                        type: string
                  policyHolder:
                    required:
                    - reference
                    type: object
                    properties:
                      reference:
                        minLength: 1
                        type: string
                  subscriber:
                    required:
                    - reference
                    type: object
                    properties:
                      reference:
                        minLength: 1
                        type: string
                  subscriberId:
                    minLength: 1
                    type: string
                  beneficiary:
                    required:
                    - reference
                    type: object
                    properties:
                      reference:
                        minLength: 1
                        type: string
                  dependent:
                    minLength: 1
                    type: string
                  relationship:
                    required:
                    - coding
                    type: object
                    properties:
                      coding:
                        minItems: 1
                        uniqueItems: true
                        type: array
                        items:
                          required:
                          - code
                          - system
                          type: object
                          properties:
                            system:
                              minLength: 1
                              type: string
                            code:
                              minLength: 1
                              type: string
                  period:
                    required:
                    - end
                    - start
                    type: object
                    properties:
                      start:
                        minLength: 1
                        type: string
                      end:
                        minLength: 1
                        type: string
                  payor:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - reference
                      type: object
                      properties:
                        reference:
                          minLength: 1
                          type: string
                  class:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - name
                      - value
                      type: object
                      properties:
                        type:
                          required:
                          - coding
                          - text
                          type: object
                          properties:
                            coding:
                              minItems: 1
                              uniqueItems: true
                              type: array
                              items:
                                required:
                                - code
                                - system
                                type: object
                                properties:
                                  system:
                                    minLength: 1
                                    type: string
                                  code:
                                    minLength: 1
                                    type: string
                            text:
                              minLength: 1
                              type: string
                        value:
                          minLength: 1
                          type: string
                        name:
                          minLength: 1
                          type: string
                  network:
                    minLength: 1
                    type: string
      description: ''
    Coverage:
      required:
      - beneficiary
      - class
      - dependent
      - id
      - identifier
      - language
      - meta
      - network
      - payor
      - period
      - policyHolder
      - relationship
      - resourceType
      - status
      - subscriber
      - subscriberId
      - text
      - type
      type: object
      properties:
        resourceType:
          minLength: 1
          type: string
        id:
          minLength: 1
          type: string
        meta:
          required:
          - lastUpdated
          - profile
          type: object
          properties:
            lastUpdated:
              minLength: 1
              type: string
            profile:
              type: array
              items:
                type: object
                properties: {}
        language:
          minLength: 1
          type: string
        text:
          required:
          - div
          - status
          type: object
          properties:
            status:
              minLength: 1
              type: string
            div:
              minLength: 1
              type: string
        identifier:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - system
            - value
            type: object
            properties:
              type:
                required:
                - coding
                type: object
                properties:
                  coding:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - code
                      - system
                      type: object
                      properties:
                        system:
                          minLength: 1
                          type: string
                        code:
                          minLength: 1
                          type: string
              system:
                minLength: 1
                type: string
              value:
                minLength: 1
                type: string
        status:
          minLength: 1
          type: string
        type:
          required:
          - coding
          - text
          type: object
          properties:
            coding:
              minItems: 1
              uniqueItems: true
              type: array
              items:
                required:
                - code
                - system
                type: object
                properties:
                  system:
                    minLength: 1
                    type: string
                  code:
                    minLength: 1
                    type: string
            text:
              minLength: 1
              type: string
        policyHolder:
          required:
          - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
        subscriber:
          required:
          - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
        subscriberId:
          minLength: 1
          type: string
        beneficiary:
          required:
          - reference
          type: object
          properties:
            reference:
              minLength: 1
              type: string
        dependent:
          minLength: 1
          type: string
        relationship:
          required:
          - coding
          type: object
          properties:
            coding:
              minItems: 1
              uniqueItems: true
              type: array
              items:
                required:
                - code
                - system
                type: object
                properties:
                  system:
                    minLength: 1
                    type: string
                  code:
                    minLength: 1
                    type: string
        period:
          required:
          - end
          - start
          type: object
          properties:
            start:
              minLength: 1
              type: string
            end:
              minLength: 1
              type: string
        payor:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - reference
            type: object
            properties:
              reference:
                minLength: 1
                type: string
        class:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            required:
            - name
            - value
            type: object
            properties:
              type:
                required:
                - coding
                - text
                type: object
                properties:
                  coding:
                    minItems: 1
                    uniqueItems: true
                    type: array
                    items:
                      required:
                      - code
                      - system
                      type: object
                      properties:
                        system:
                          minLength: 1
                          type: string
                        code:
                          minLength: 1
                          type: string
                  text:
                    minLength: 1
                    type: string
              value:
                minLength: 1
                type: string
              name:
                minLength: 1
                type: string
        network:
          minLength: 1
          type: string
      description: ''
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
